STATE_MODIFIERS_MAPPINGS = {
    "FATIGUE": 2.3,
    "MULTITASKING": 2.2,
    "COGNITIVE OVERLOAD": 2.1,
    "STRESS": 1.3,
    "COGNITIVE LOAD": 1.2,
    "RUSHING": 1.2,
    "ALERT FATIGUE": 1.0,
    "PRIORITIZATION ERRORS": 1.0,
    "CONFIRMATION BIAS": 1.0,
    "COMMUNICATION FAILURE": 1.0,
    "AUTOMATION BIAS": 1.0,
    "COMMUNICATION": 1.0,
    "COMPLACENCY": 1.0,
    "BOREDOM / REPETITION": 1.0
}
